services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: keycloak-dev
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 8443:8443
      - 9443:9443
    depends_on:
      - keycloak-db
    networks:
      - keycloak-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - keycloak-net

volumes:
  keycloak_db_data:

networks:
  keycloak-net: